# Generated by Django 3.2.5 on 2021-08-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_libro_descri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descri',
            field=models.CharField(max_length=255),
        ),
    ]
