# Generated by Django 3.2.5 on 2021-08-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_alter_libro_descri'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='notas',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
